### ISSUE TITLE
Matrix is not normalised for whitepoint

### ISSUE THREAD

**Issue by KelSolaar** [ampas/idt-calculator#55]
Hi,

I just noted we do not normalise the matrix for whitepoint so I rolled a small function to do that in Colour: https://github.com/colour-science/colour/blob/develop/colour/characterisation/aces_it.py#L747 It should not really change the results much but it is something commonly done. @aforsythe for VIS.

https://github.com/ampas/idt-calculator/blob/82f23b8966309b4484a517bdcbdc1d26477ec0ba/aces/idt/prosumer_camera.py#L1096

Cheers,

Thomas

**Comment by KelSolaar** [comment]
So, having rolled that as a test in the calculator, its seems to perform much much worse with than without:

**With**
![image](https://user-images.githubusercontent.com/99779/233767102-7073b17d-ad7e-48ac-81aa-f41a8794b80d.png)

**Without**
![image](https://user-images.githubusercontent.com/99779/233767127-c0dfd913-ff55-4406-915e-fbdf9d2c3fcf.png)

**Comment by aforsythe** [comment]
I'm a little confused ... I saw the commit and merged it, but then when I came into github I didn't see a closed PR.  Was there a PR?  Did I jump the gun?

**Comment by KelSolaar** [comment]
Ah! Yeah there were no PR up, only a branch I pushed, it is fine if it is merged though, I implemented support for it but it is not on by default on the calculator. I think we should have a good discussion about it though as it seems to affect performance heavily.

**Comment by KelSolaar** [comment]
This was implemented thus we can close!
