### ISSUE TITLE
Prosumer IDTs are clamped at 1.0

### ISSUE THREAD

**Issue by nick-shaw** [ampas/idt-calculator#75]
https://github.com/ampas/idt-calculator/blob/55c59d74149c2d32c3604e7d11cbb93a95849a54/aces/idt/prosumer_camera.py#L1404

The range element at the end of the prosumer CLF IDT is unnecessary, and is fact in set to clamp the output to a maximum value of 1.0, which is clearly undesirable in an ACES IDT.

**Comment by KelSolaar** [comment]
This was fixed in #76.
